### ISSUE TITLE
How are the settings in "Contributions" build?

### ISSUE THREAD

**Issue by andre2007** [d-language-server/vscode-dlang#16]
I do not know the Language Server Protocol, but are the settings in "Contributions" hardcoded or are they retrieved from Language Server DLS?

I ask because if they are retrieved from DLS, i would create a feature request for https://github.com/gtache/intellij-lsp to also support automatically showing all 
settings.

**Comment by LaurentTreguier** [comment]
I don't really understand your question. What do you mean by "Contributions" ?

**Comment by andre2007** [comment]
In the tabstrip "Contributions" the settings of DLS are shown. I was wondering whether these settings are automatically retrieved by means of a Language Server Protocol or you hard coded each setting:

![image](https://user-images.githubusercontent.com/1451047/62776274-613b6580-baaa-11e9-9417-49d3f7211018.png)

**Comment by LaurentTreguier** [comment]
Oh I see; this tab is part of how VSCode handles its extensions. Any type of extension will have a "Contributions" tab showing its settings, language grammars and the commands it adds to the editor. The settings are [not specified by the LSP](https://microsoft.github.io/language-server-protocol/specification#workspace_didChangeConfiguration), every server simply documents whatever settings they have implemented, and those are then typically filled out in JSON format directly by the user.
With intellij-lsp, I'm not sure how configuration is handled. Searching for `didChangeConfiguration` yields some results, so it looks like it's implemented, but I can't find out how you can specify a configuration for a server.

**Comment by andre2007** [comment]
Thanks a lot. I close this issue as the question is clarified .
