### ISSUE TITLE
d.dls.symbol.importPaths Does Not Work Properly

### ISSUE THREAD

**Issue by DougClayton4231** [d-language-server/vscode-dlang#17]
I've been getting an odd issue with vscode version 1.37.1 and vscode-dlang version 1.16.6.

I have 16 different paths, split between 3 different subfolders, added to my workspace json file.  All of the symbols located in the first subfolder work correctly with autocomplete, but any files located in the other two subfolders do not work at all. I've checked and rechecked all of the paths but I haven't been able to find a solution for getting the import paths to work. I've tried uninstalling, cleaning the dub folder and reinstalling but to no avail.

Here's an example of how the settings look:
`"d.dls.symbol.importPaths": [
            "./source/",
            "./source/path_one/",
            "./source/path_one/folder1/",
            "./source/path_one/folder2/",
            "./source/path_one/folder3/",
            "./source/path_one/folder4/",
            "./source/path_one/folder5/",
            "./source/path_one/folder6/",
            "./source/path_one/folder7/",
            "./source/path_one/folder8/",
            "./source/path_one/folder9/",
            "./source/path_two/folder1/",
            "./source/path_two/folder2/",
            "./source/path_two/folder3/",
            "./source/path_three/folder1/",
            "./source/path_three/folder2/",
        ],`

**Comment by LaurentTreguier** [comment]
If it is a single dub project, then you shouldn't have to use `d.dls.symbol.importPaths`, it's supposed to be able to detect things like subprojects. What does your `dub.json` file look like ?

**Comment by DougClayton4231** [comment]
Ah, maybe that's it. I'm using a single dub project but I wasn't using the sourcePath and importPath fields. I'll check to see if I can get it working with dub.

**Comment by DougClayton4231** [comment]
No luck with that either.

My dub.json looks like this:
`"mainSourceFile": "source/engine.d",
    "targetName": "engine",
    "targetPath": "bin/",
    "targetType": "executable",
    "workingDirectory": "temp/",
    "sourcePaths": [
        "source/engine/ai",
        "source/engine/audio",
        "source/engine/collision",
        "source/engine/common",
        "source/engine/io",
        "source/engine/math",
        "source/engine/platform",
        "source/engine/rendering",
        "source/engine/world",
        "source/thirdparty/directx/",
        "source/thirdparty/glfw/",
        "source/thirdparty/vulkan/",
        "source/tools/assets/",
        "source/tools/loader/"
    ],
    "importPaths": [
        "source/engine/ai",
        "source/engine/audio",
        "source/engine/collision",
        "source/engine/common",
        "source/engine/io",
        "source/engine/math",
        "source/engine/platform",
        "source/engine/rendering",
        "source/engine/world",
        "source/thirdparty/directx/",
        "source/thirdparty/glfw/",
        "source/thirdparty/vulkan/",
        "source/tools/assets/",
        "source/tools/loader/"
    ]`

**Comment by LaurentTreguier** [comment]
This technically doesn't solve the problem, and it's not my place to say, but looking at your organization, maybe dividing it into one main project (`engine`) and two sub-projects (`thirdparty` and `tools`) might work.
There probably shouldn't be `sourcePaths` and `importPaths` duplicating the paths, but that's probably not the cause of the problem.

A quick question: in `source/engine/world` for example, are the source files supposed to be in a `world.a.b.c` module, or is `world` not supposed to be part of the package name ?

**Comment by DougClayton4231** [comment]
I'll give that a shot. Under `world`, the organization would be `world.a.b.c`.

The thing that was odd was, all of this was working fine on my end until this morning, so I have no idea what could have changed that broke it. I figure I'll just close the issue and do a refactor :)

Thanks so much for your help!

**Comment by LaurentTreguier** [comment]
If so, then the `sourcePaths`/`importPaths` should probably be pointing to the 3 main directories, as they are the actual roots of the sources.
Don't hesitate to re-open if the issue continues to give you trouble !
