### ISSUE TITLE
No linting at all in ubuntu

### ISSUE THREAD

**Issue by HossainAdnan** [d-language-server/vscode-dlang#18]
```D
import doesntexist;

void main()
{
	float x = "string";
	x ~= [new Exception(-77)];
	writeln(x);
}
```

```
(dmd-2.088.0)user0@pop-os:~$ serve-d --version && dub --version && dmd --version
serve-d v0.4.1 with workspace-d v3.3.0
Included features: "d", "workspaces"
Built: Tue Sep 24 16:30:47 2019
DUB version 1.17.0, built on Sep  1 2019
DMD64 D Compiler v2.088.0
Copyright (C) 1999-2019 by The D Language Foundation, All Rights Reserved written by Walter Bright
(dmd-2.088.0)user0@pop-os:~/vscproj/events$ cat -n dub.json 
     1  {
     2          "authors": [
     3                  "9898287"
     4          ],
     5          "copyright": "Copyright © 2019, 9898287",
     6          "description": "\"Alarm/Reminder app for Linux\"",
     7          "license": "MIT",
     8          "name": "events"
     9  }
```

More info
```json
    "d.servedPath": "/usr/bin/serve-d",
    "d.dcdClientPath": "/home/user0/.local/share/code-d/bin/dcd-client",
    "d.dcdServerPath": "/home/user0/.local/share/code-d/bin/dcd-server",
    "d.dscannerPath": "/usr/bin/dscanner",
    "d.dubPath": "/home/user0/dlang/dmd-2.088.0/linux/bin64/dub",
    "[d]": {
        "editor.defaultFormatter": "webfreak.code-d"
    }

```

```
(dmd-2.088.0)user0@pop-os:~$ dscanner --version
v0.8.0-4-gd4dd5b9
(dmd-2.088.0)user0@pop-os:~$ ~/.local/share/code-d/bin/dcd-server --version
v0.11.1
(dmd-2.088.0)user0@pop-os:~$ ~/.local/share/code-d/bin/dcd-client --version
v0.11.1
(dmd-2.088.0)user0@pop-os:~$ 
```
Since ubuntu's `dub` was broken, I manually installed `dmd` and `dub` from the `install.sh`. There was no linting then so built `serve-d` with `dub build --build=release-nobounds` and manually put the generated binary to `/usr/bin`. 

Formatting seems to work.

Is there something I'm missing?

**Comment by LaurentTreguier** [comment]
This plugin doesn't use serve-d; use [code-d](https://marketplace.visualstudio.com/items?itemName=webfreak.code-d) to use serve-d

**Comment by HossainAdnan** [comment]
Fedora 30, issue persists. No linting in either code-d and vscode-dlang.
dmd, dub and vs code installed through snaps.

**Comment by LaurentTreguier** [comment]
Regarding the code example you posted in the first comment, it's normal to not have any linting: D-Scanner doesn't do deep enough code analysis to see what's wrong with it. If you reduce it to this:
```d
void main()
{
	float x = "string";
}
```
Then it should be say that `x` is unused and could have been declared as `const` or `immutable`. (and if it still doesn't show anything then something is wrong indeed).

However if it stops at "loading DLS", I don't know what is happening. Have you tried uninstalling and re-installing the extension ? I know it sounds a bit stupid, but in the past I did encounter cases where an extension had simply been installed incorrectly by VSCode (with things like missing files).

What baffles me a bit is that I spent most of my time developing DLS and vscode-dlang on Fedora, so this should be the most well-tested platform. I did install dmd differently (I maintain some [DMD and Dub RPM packages in Copr](https://copr.fedorainfracloud.org/coprs/tcg/devel/)), but I don't think this should make a difference.

Another question to be sure about what the extension does: what does `ls $HOME/.dub/packages/.bin` tell you ?

**Comment by HossainAdnan** [comment]
Ok I ended up re-installing ubuntu again. When I installed `dmd` and `dub` through snap, I tried bootstraping `dls` it failed. VS Code (snap package) fails to find dub in the `PATH` even though it was, under the `~/snap` directory.

So I installed dmd and dub through the installer script and this time the `dls` builds and runs (`dub run dls:bootstrap`).

I installed the `.deb` package of VS Code since snap was giving me issues. This time it says "building DLS" after reinstalling the extension.

```D
void main()
{
	float x = "string";
}
``` 
Also says that the x is never used and could be a const. 

Closing.

**Comment by HossainAdnan** [comment]
> Another question to be sure about what the extension does: what does `ls $HOME/.dub/packages/.bin` tell you ?

Just revisiting this issue, if I install dmd, dub and code through snaps, vscode always starts out saying "installing DLS" and then it says "starting dls" in the statusbar down below.

![` ls $HOME/.dub/packages/.bin` returns nothing.](https://i.imgur.com/Adq5iky.png)

**Comment by LaurentTreguier** [comment]
Small update: the snap packages aren't that outdated when using the `edge` channel. The problem seems to come from a confusion between the libs used by the Dub snap and the system libs; if you run `dub build dls:bootstrap` and then run the binary manually with `$HOME./.dub/packages/dls-0.25.17/dls/bootstrap/dls_bootstrap`, it does install DLS properly
