### ISSUE TITLE
No completion for local dependency

### ISSUE THREAD

**Issue by RUSshy** [d-language-server/vscode-dlang#2]
Hi

I have a project with 3 subproject

- mygame
- mylib
- myserver

mygame have mylib as local dependency

```json
{
	"name": "mygame",
	"authors": [
		"test"
	],
	"description": "A minimal D application.",
	"copyright": "Copyright © 2018, test",
	"license": "proprietary",
	"dependencies": {
		"somethingd:mylib": { "path": "../mylib"  }
		
	}
}
```

Let's say i have this code:

```d
import std.stdio;

// module from mylib
import data;

void main()
{
	auto data = new EntityData;
	data.id = 99;
	
	writeln("i am mygame");
	writeln("entityData: ", data.id);
}
```

Code compile and run, but i vscode doesn't understand what is module data and class EntityData, there is no code completion for it

Here is project: 

[somethingD.zip](https://github.com/LaurentTreguier/vscode-dls/files/2109172/somethingD.zip)

I'm not experienced with d, so i don't know if it is how it should be done(local dependency)

I want to do like in C#  where i can have multiple projects in a solution

**Comment by LaurentTreguier** [comment]
I'll need to add support for `"path"` in DLS. However, for this case, since you are using your own subpackages, I'd suggest you use something like this instead:
```json
{
	"name": "mygame",
	"authors": [
		"test"
	],
	"description": "A minimal D application.",
	"copyright": "Copyright © 2018, test",
	"license": "proprietary",
	"dependencies": {
		"somethingd:mylib": "*"
	},
	"subPackages": [
		"../mylib"
	]
}
```
This is the recommended way if you're writing the subpackages yourself (see [here](https://code.dlang.org/package-format?lang=json#sub-packages)).

But I'll add support for `"path"` nonetheless, as it's perfectly valid as well

**Comment by LaurentTreguier** [comment]
That's weird, I'm not getting this. Is there any specific action you can pinpoint that trigger it ? Or is it at startup, instantly ?

Also, I didn't see that you had already put `mylib` and the rest as subpackages in the main `dub.json`, so it doesn't make sense to include it in `mygame`'s `dub.json`, my bad. So the subpackages part in the `dub.json` I wrote up there shouldn't be there.

**Comment by RUSshy** [comment]
Once i remove the ``subPackages`` part it now start without error

But it still don't recognise ``EntityData``

![code_2018-06-17_20-15-19](https://user-images.githubusercontent.com/18348637/41510832-982cc576-726b-11e8-85de-280ff6c5b00b.png)

**Comment by LaurentTreguier** [comment]
For now, DLS 0.6.2 should enable completion with subpackages importing other subpackages.

**Comment by RUSshy** [comment]
It works now, thanks a lot :D :D

**Comment by LaurentTreguier** [comment]
> It works now
At least, until it crashes because of another bug 😅

**Comment by RUSshy** [comment]
Is path support added ?

I am unable to get code completion for my local library ``sandbox`` from ``samples/hello_0``

And i can't seems to remember what i did as workaround last time :(

**Comment by LaurentTreguier** [comment]
I've tried setting `d.init.autoImports` to `false` and `d.dls.symbol.importPaths` to `["sandbox", "samples/hello_0"]`. I could jump to symbol definitions from `sandbox`, but couldn't get completion to work.
I'm really starting to wonder if something in `sandbox` simply triggers a bug in DCD.

**Comment by LaurentTreguier** [comment]
Oooh, no I see the problem. You simply forgot to add a directory: you have `sandbox/source/[...].d` when you should have `sandbox/source/sandbox/[...].d`. Otherwise you would have to `import core;` instead of `import sandbox.core`

**Comment by RUSshy** [comment]
Ohh you are right, it works now !!! thanks !! :D

**Comment by RUSshy** [comment]
I think this issue can be closed now, it seems to be fully supported now

**Comment by RUSshy** [comment]
Offtopic question: is there a gitter room for DLS or the vscode plugin ?

**Comment by LaurentTreguier** [comment]
Nope, there is no gitter/discord/anything
